language:
	node_js
before_install:
	eslint ./public/javascripts *.js --fix >> lintOuput.txt
install:
	npm install
script:
	npm test
deploy:
	skip_cleanup: true
	firebase serve --only functions,hosting
